from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models import User, Listing


async def seed_database(db: AsyncSession):
    result = await db.execute(select(User))
    existing_users = result.scalars().all()

    if existing_users:
        return

    host = User(
        full_name="Rahul Sharma",
        email="host@stayfinder.com",
        avatar="https://i.pravatar.cc/150?img=12",
        is_host=True,
    )

    db.add(host)
    await db.flush()

    listings = [
       Listing(
    title="Luxury Beach Villa",
    description="Beautiful beachfront villa with a private pool and sunset views.",
    location="Goa",
    property_type="Villa",
    image_url="https://images.pexels.com/photos/7031408/pexels-photo-7031408.jpeg",
    price_per_night=8500,
    rating=4.9,
    reviews_count=210,
    bedrooms=3,
    bathrooms=2,
    beds=3,
    max_guests=6,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=True,
    air_conditioning=True,
    host_id=host.id,
),

Listing(
    title="Snow View Chalet",
    description="Cozy chalet overlooking the Himalayas.",
    location="Manali",
    property_type="Cabin",
    image_url="https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg",
    price_per_night=5200,
    rating=4.8,
    reviews_count=156,
    bedrooms=2,
    bathrooms=2,
    beds=2,
    max_guests=4,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=False,
    air_conditioning=False,
    host_id=host.id,
),

Listing(
    title="Lake View Cottage",
    description="Peaceful cottage overlooking Ooty Lake.",
    location="Ooty",
    property_type="Cottage",
    image_url="https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg",
    price_per_night=5100,
    rating=4.9,
    reviews_count=180,
    bedrooms=2,
    bathrooms=2,
    beds=2,
    max_guests=5,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=False,
    air_conditioning=True,
    host_id=host.id,
),

Listing(
    title="Royal Palace Stay",
    description="Experience royal luxury in the heart of Rajasthan.",
    location="Udaipur",
    property_type="Palace",
    image_url="https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg",
    price_per_night=9800,
    rating=5.0,
    reviews_count=240,
    bedrooms=4,
    bathrooms=4,
    beds=4,
    max_guests=8,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=True,
    air_conditioning=True,
    host_id=host.id,
),

Listing(
    title="Coffee Estate Retreat",
    description="Stay among lush coffee plantations.",
    location="Coorg",
    property_type="Farm Stay",
    image_url="https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
    price_per_night=4300,
    rating=4.8,
    reviews_count=167,
    bedrooms=2,
    bathrooms=2,
    beds=2,
    max_guests=5,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=False,
    air_conditioning=False,
    host_id=host.id,
),

Listing(
    title="Skyline Penthouse",
    description="Luxury penthouse with city skyline views.",
    location="Mumbai",
    property_type="Apartment",
    image_url="https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg",
    price_per_night=10500,
    rating=4.9,
    reviews_count=198,
    bedrooms=3,
    bathrooms=3,
    beds=3,
    max_guests=6,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=True,
    air_conditioning=True,
    host_id=host.id,
),

Listing(
    title="Tea Garden Bungalow",
    description="Colonial bungalow inside tea plantations.",
    location="Darjeeling",
    property_type="Bungalow",
    image_url="https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg",
    price_per_night=5600,
    rating=4.8,
    reviews_count=141,
    bedrooms=3,
    bathrooms=2,
    beds=3,
    max_guests=6,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=False,
    air_conditioning=False,
    host_id=host.id,
),

Listing(
    title="Backwater Houseboat",
    description="Cruise through Kerala's scenic backwaters.",
    location="Alleppey",
    property_type="Boat",
    image_url="https://images.pexels.com/photos/1001682/pexels-photo-1001682.jpeg",
    price_per_night=7600,
    rating=4.9,
    reviews_count=188,
    bedrooms=2,
    bathrooms=2,
    beds=2,
    max_guests=4,
    wifi=True,
    kitchen=False,
    parking=False,
    pool=False,
    air_conditioning=True,
    host_id=host.id,
),Listing(
    title="Desert Camp Retreat",
    description="Luxury desert tents under the stars.",
    location="Jaisalmer",
    property_type="Tent",
    image_url="https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg",
    price_per_night=4500,
    rating=4.8,
    reviews_count=148,
    bedrooms=1,
    bathrooms=1,
    beds=2,
    max_guests=3,
    wifi=False,
    kitchen=False,
    parking=True,
    pool=False,
    air_conditioning=False,
    host_id=host.id,
),

Listing(
    title="Forest Eco Lodge",
    description="Stay surrounded by lush forests and wildlife.",
    location="Wayanad",
    property_type="Lodge",
    image_url="https://images.pexels.com/photos/731082/pexels-photo-731082.jpeg",
    price_per_night=4800,
    rating=4.9,
    reviews_count=172,
    bedrooms=2,
    bathrooms=2,
    beds=2,
    max_guests=5,
    wifi=False,
    kitchen=True,
    parking=True,
    pool=False,
    air_conditioning=False,
    host_id=host.id,
),

Listing(
    title="Beachfront Apartment",
    description="Modern apartment overlooking the Arabian Sea.",
    location="Kovalam",
    property_type="Apartment",
    image_url="https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg",
    price_per_night=5400,
    rating=4.8,
    reviews_count=136,
    bedrooms=2,
    bathrooms=2,
    beds=2,
    max_guests=4,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=False,
    air_conditioning=True,
    host_id=host.id,
),

Listing(
    title="Riverfront Homestay",
    description="Calm riverside retreat perfect for families.",
    location="Rishikesh",
    property_type="House",
    image_url="https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg",
    price_per_night=3900,
    rating=4.7,
    reviews_count=104,
    bedrooms=2,
    bathrooms=2,
    beds=2,
    max_guests=5,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=False,
    air_conditioning=False,
    host_id=host.id,
),

Listing(
    title="Island Paradise",
    description="Luxury island villa with crystal-clear waters.",
    location="Lakshadweep",
    property_type="Villa",
    image_url="https://images.pexels.com/photos/1268855/pexels-photo-1268855.jpeg",
    price_per_night=11800,
    rating=5.0,
    reviews_count=281,
    bedrooms=4,
    bathrooms=4,
    beds=4,
    max_guests=8,
    wifi=True,
    kitchen=True,
    parking=False,
    pool=True,
    air_conditioning=True,
    host_id=host.id,
),

Listing(
    title="Heritage Haveli",
    description="Traditional Rajasthani haveli with royal interiors.",
    location="Jaipur",
    property_type="Villa",
    image_url="https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg",
    price_per_night=6900,
    rating=4.8,
    reviews_count=154,
    bedrooms=3,
    bathrooms=3,
    beds=3,
    max_guests=6,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=False,
    air_conditioning=True,
    host_id=host.id,
),

Listing(
    title="Cliffside Villa",
    description="Luxury villa with breathtaking sunset views.",
    location="Varkala",
    property_type="Villa",
    image_url="https://images.pexels.com/photos/2581922/pexels-photo-2581922.jpeg",
    price_per_night=7300,
    rating=4.9,
    reviews_count=194,
    bedrooms=3,
    bathrooms=2,
    beds=3,
    max_guests=6,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=True,
    air_conditioning=True,
    host_id=host.id,
),

Listing(
    title="Modern City Loft",
    description="Minimalist loft in the heart of the city.",
    location="Bangalore",
    property_type="Loft",
    image_url="https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg",
    price_per_night=4200,
    rating=4.7,
    reviews_count=127,
    bedrooms=1,
    bathrooms=1,
    beds=1,
    max_guests=2,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=False,
    air_conditioning=True,
    host_id=host.id,
),Listing(
    title="Ocean Breeze Villa",
    description="Private beachfront villa with infinity pool.",
    location="Andaman",
    property_type="Villa",
    image_url="https://images.pexels.com/photos/32870/pexels-photo.jpg",
    price_per_night=12500,
    rating=5.0,
    reviews_count=312,
    bedrooms=4,
    bathrooms=4,
    beds=4,
    max_guests=8,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=True,
    air_conditioning=True,
    host_id=host.id,
),

Listing(
    title="Hilltop Glass Cabin",
    description="Modern glass cabin with panoramic mountain views.",
    location="Nainital",
    property_type="Cabin",
    image_url="https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg",
    price_per_night=5900,
    rating=4.9,
    reviews_count=168,
    bedrooms=2,
    bathrooms=2,
    beds=2,
    max_guests=4,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=False,
    air_conditioning=False,
    host_id=host.id,
),

Listing(
    title="Royal Fort Residency",
    description="Historic fort converted into a luxury heritage hotel.",
    location="Jodhpur",
    property_type="Castle",
    image_url="https://images.pexels.com/photos/534151/pexels-photo-534151.jpeg",
    price_per_night=9300,
    rating=4.9,
    reviews_count=221,
    bedrooms=4,
    bathrooms=3,
    beds=4,
    max_guests=8,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=True,
    air_conditioning=True,
    host_id=host.id,
),

Listing(
    title="Tea Garden Retreat",
    description="Relax among endless tea plantations.",
    location="Munnar",
    property_type="Cottage",
    image_url="https://images.pexels.com/photos/462235/pexels-photo-462235.jpeg",
    price_per_night=4700,
    rating=4.8,
    reviews_count=150,
    bedrooms=2,
    bathrooms=2,
    beds=2,
    max_guests=4,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=False,
    air_conditioning=False,
    host_id=host.id,
),

Listing(
    title="Sunset Lake House",
    description="Luxury lakeside house with private deck.",
    location="Udaipur",
    property_type="House",
    image_url="https://images.pexels.com/photos/209296/pexels-photo-209296.jpeg",
    price_per_night=6900,
    rating=4.9,
    reviews_count=201,
    bedrooms=3,
    bathrooms=3,
    beds=3,
    max_guests=6,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=False,
    air_conditioning=True,
    host_id=host.id,
),

Listing(
    title="Heritage Mansion",
    description="Beautiful colonial mansion with antique interiors.",
    location="Mysore",
    property_type="Mansion",
    image_url="https://images.pexels.com/photos/53610/large-home-residential-house-architecture-53610.jpeg",
    price_per_night=8100,
    rating=4.8,
    reviews_count=172,
    bedrooms=4,
    bathrooms=3,
    beds=4,
    max_guests=8,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=True,
    air_conditioning=True,
    host_id=host.id,
),

Listing(
    title="Luxury Studio Apartment",
    description="Modern apartment perfect for business travelers.",
    location="Hyderabad",
    property_type="Apartment",
    image_url="https://images.pexels.com/photos/271743/pexels-photo-271743.jpeg",
    price_per_night=3700,
    rating=4.7,
    reviews_count=108,
    bedrooms=1,
    bathrooms=1,
    beds=1,
    max_guests=2,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=True,
    air_conditioning=True,
    host_id=host.id,
),

Listing(
    title="Valley View Cottage",
    description="Wooden cottage surrounded by pine forests.",
    location="Shimla",
    property_type="Cottage",
    image_url="https://images.pexels.com/photos/280229/pexels-photo-280229.jpeg",
    price_per_night=5400,
    rating=4.8,
    reviews_count=161,
    bedrooms=2,
    bathrooms=2,
    beds=2,
    max_guests=5,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=False,
    air_conditioning=False,
    host_id=host.id,
),Listing(
    title="Treehouse Escape",
    description="Luxury treehouse nestled deep in the forest.",
    location="Coorg",
    property_type="Treehouse",
    image_url="https://images.pexels.com/photos/323775/pexels-photo-323775.jpeg",
    price_per_night=6800,
    rating=4.9,
    reviews_count=214,
    bedrooms=2,
    bathrooms=1,
    beds=2,
    max_guests=4,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=False,
    air_conditioning=False,
    host_id=host.id,
),

Listing(
    title="Luxury Farmhouse",
    description="Spacious farmhouse surrounded by greenery.",
    location="Sakleshpur",
    property_type="Farm Stay",
    image_url="https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg",
    price_per_night=5200,
    rating=4.8,
    reviews_count=176,
    bedrooms=3,
    bathrooms=2,
    beds=3,
    max_guests=6,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=True,
    air_conditioning=True,
    host_id=host.id,
),

Listing(
    title="Beach Paradise Cottage",
    description="Wake up to the sound of waves every morning.",
    location="Pondicherry",
    property_type="Cottage",
    image_url="https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg",
    price_per_night=4900,
    rating=4.8,
    reviews_count=152,
    bedrooms=2,
    bathrooms=2,
    beds=2,
    max_guests=4,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=False,
    air_conditioning=True,
    host_id=host.id,
),

Listing(
    title="Snow Resort",
    description="Luxury stay surrounded by snow-covered peaks.",
    location="Gulmarg",
    property_type="Resort",
    image_url="https://images.pexels.com/photos/355465/pexels-photo-355465.jpeg",
    price_per_night=8900,
    rating=4.9,
    reviews_count=241,
    bedrooms=3,
    bathrooms=3,
    beds=3,
    max_guests=6,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=False,
    air_conditioning=True,
    host_id=host.id,
),

Listing(
    title="Heritage Bungalow",
    description="Vintage bungalow with classic architecture.",
    location="Kodaikanal",
    property_type="Bungalow",
    image_url="https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg",
    price_per_night=5700,
    rating=4.8,
    reviews_count=162,
    bedrooms=3,
    bathrooms=2,
    beds=3,
    max_guests=5,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=False,
    air_conditioning=False,
    host_id=host.id,
),

Listing(
    title="Safari Jungle Camp",
    description="Experience wildlife like never before.",
    location="Bandipur",
    property_type="Camp",
    image_url="https://images.pexels.com/photos/2476632/pexels-photo-2476632.jpeg",
    price_per_night=6100,
    rating=4.9,
    reviews_count=183,
    bedrooms=2,
    bathrooms=2,
    beds=2,
    max_guests=4,
    wifi=False,
    kitchen=False,
    parking=True,
    pool=False,
    air_conditioning=False,
    host_id=host.id,
),

Listing(
    title="Luxury Cliff Villa",
    description="Infinity pool with breathtaking sea views.",
    location="Goa",
    property_type="Villa",
    image_url="https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg",
    price_per_night=13500,
    rating=5.0,
    reviews_count=325,
    bedrooms=5,
    bathrooms=5,
    beds=5,
    max_guests=10,
    wifi=True,
    kitchen=True,
    parking=True,
    pool=True,
    air_conditioning=True,
    host_id=host.id,
),

Listing(
    title="Glass Dome Stay",
    description="Sleep under the stars in a luxury glass dome.",
    location="Spiti Valley",
    property_type="Dome",
    image_url="https://images.pexels.com/photos/1732414/pexels-photo-1732414.jpeg",
    price_per_night=7200,
    rating=4.9,
    reviews_count=145,
    bedrooms=1,
    bathrooms=1,
    beds=1,
    max_guests=2,
    wifi=True,
    kitchen=False,
    parking=True,
    pool=False,
    air_conditioning=False,
    host_id=host.id,
),
    ]

    db.add_all(listings)

    await db.commit()